"""PDF generation using WeasyPrint (HTML → PDF)."""

import io
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


def _generate_html_report(title: str, sections: list[dict]) -> str:
    """Generate a simple HTML report."""
    html = f"""<!DOCTYPE html>
<html>
<head>
<style>
  body {{ font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #1a1a1a; }}
  h1 {{ color: #0A1628; border-bottom: 2px solid #3B82F6; padding-bottom: 10px; }}
  h2 {{ color: #1F2937; margin-top: 30px; }}
  h3 {{ color: #374151; }}
  .meta {{ color: #64748B; font-size: 12px; margin-bottom: 20px; }}
  .section {{ margin-bottom: 24px; }}
  .confidence {{ display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: bold; }}
  .high {{ background: #DCFCE7; color: #166534; }}
  .medium {{ background: #FEF9C3; color: #854D0E; }}
  .low {{ background: #FEE2E2; color: #991B1B; }}
  ul {{ padding-left: 20px; }}
  li {{ margin-bottom: 6px; }}
  .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #E5E7EB; color: #9CA3AF; font-size: 11px; text-align: center; }}
  .watermark {{ position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-30deg); font-size: 80px; color: rgba(0,0,0,0.03); z-index: -1; }}
</style>
</head>
<body>
<h1>{title}</h1>
<div class="meta">Generated by Gravix • {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</div>
"""
    for section in sections:
        html += f'<div class="section">'
        if section.get("heading"):
            html += f'<h2>{section["heading"]}</h2>'
        if section.get("content"):
            html += f'<p>{section["content"]}</p>'
        if section.get("items"):
            html += "<ul>"
            for item in section["items"]:
                html += f"<li>{item}</li>"
            html += "</ul>"
        html += "</div>"

    html += '<div class="footer">© Gravix — Industrial Materials Intelligence</div>'
    html += "</body></html>"
    return html


def generate_analysis_pdf(analysis: dict, is_free: bool = True) -> bytes:
    """Generate a PDF report for a failure analysis."""
    try:
        from weasyprint import HTML
    except ImportError:
        logger.warning("WeasyPrint not available, generating placeholder PDF")
        return _placeholder_pdf("Failure Analysis Report")

    sections = []

    # Summary
    confidence = analysis.get("confidence_score", 0)
    sections.append({
        "heading": "Analysis Summary",
        "content": f"Material: {analysis.get('material_category', 'N/A')} | "
                   f"Failure Mode: {analysis.get('failure_mode', 'N/A')} | "
                   f"Confidence: {int(confidence * 100) if confidence else 'N/A'}%",
    })

    # Root causes
    root_causes = analysis.get("root_causes", [])
    if root_causes:
        sections.append({
            "heading": "Root Causes",
            "items": [
                f"{rc.get('cause', 'Unknown')} ({int(rc.get('confidence', 0) * 100)}%) — {rc.get('explanation', '')}"
                for rc in root_causes
            ],
        })

    # Contributing factors
    factors = analysis.get("contributing_factors", [])
    if factors:
        sections.append({"heading": "Contributing Factors", "items": factors})

    # Recommendations
    recs = analysis.get("recommendations", [])
    if recs:
        sections.append({
            "heading": "Recommendations",
            "items": [
                f"[{r.get('priority', 'medium')}] {r.get('title', '')}: {r.get('description', '')}"
                for r in recs
            ],
        })

    # Prevention plan
    plan = analysis.get("prevention_plan")
    if plan:
        sections.append({"heading": "Prevention Plan", "content": plan})

    title = "Failure Analysis Report"
    if is_free:
        title += " (Free Tier)"

    html = _generate_html_report(title, sections)

    pdf_bytes = HTML(string=html).write_pdf()
    return pdf_bytes


def generate_spec_pdf(spec: dict, is_free: bool = True) -> bytes:
    """Generate a PDF report for a material spec."""
    try:
        from weasyprint import HTML
    except ImportError:
        logger.warning("WeasyPrint not available, generating placeholder PDF")
        return _placeholder_pdf("Material Specification Report")

    sections = []

    # Summary
    rec_spec = spec.get("recommended_spec", {})
    sections.append({
        "heading": "Recommended Specification",
        "content": f"{rec_spec.get('title', 'N/A')} — {rec_spec.get('chemistry', 'N/A')}",
    })

    if rec_spec.get("rationale"):
        sections.append({"heading": "Rationale", "content": rec_spec["rationale"]})

    # Product characteristics
    chars = spec.get("product_characteristics", {})
    if chars:
        sections.append({
            "heading": "Key Properties",
            "items": [f"{k}: {v}" for k, v in chars.items() if v],
        })

    # Application guidance
    guidance = spec.get("application_guidance", {})
    if guidance.get("surface_prep"):
        sections.append({"heading": "Surface Preparation", "items": guidance["surface_prep"]})
    if guidance.get("application_tips"):
        sections.append({"heading": "Application Tips", "items": guidance["application_tips"]})

    # Warnings
    warnings = spec.get("warnings", [])
    if warnings:
        sections.append({"heading": "⚠ Warnings", "items": warnings})

    # Alternatives
    alts = spec.get("alternatives", [])
    if alts:
        sections.append({
            "heading": "Alternative Materials",
            "items": [
                f"{a.get('name', 'N/A')}: Pros: {', '.join(a.get('pros', []))} | Cons: {', '.join(a.get('cons', []))}"
                for a in alts
            ],
        })

    title = "Material Specification Report"
    if is_free:
        title += " (Free Tier)"

    html = _generate_html_report(title, sections)

    pdf_bytes = HTML(string=html).write_pdf()
    return pdf_bytes


def _placeholder_pdf(title: str) -> bytes:
    """Generate a minimal placeholder PDF when WeasyPrint is unavailable."""
    # Minimal valid PDF
    content = f"""%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length 44 >>
stream
BT /F1 24 Tf 72 720 Td ({title}) Tj ET
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000266 00000 n 
0000000360 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
441
%%EOF"""
    return content.encode("latin-1")
