"""PDF report generation service for 8D investigations.

Sprint 8: Uses WeasyPrint to render HTML → PDF for 8D reports.
Supports multiple templates: Generic 8D and Ford Global 8D.
"""

import logging
from datetime import datetime, timezone
from io import BytesIO
from typing import Optional

from weasyprint import HTML, CSS
from database import get_supabase

logger = logging.getLogger(__name__)


def _format_date(dt_str: Optional[str]) -> str:
    """Format ISO datetime string to readable date."""
    if not dt_str:
        return "N/A"
    try:
        dt = datetime.fromisoformat(dt_str.replace("Z", "+00:00"))
        return dt.strftime("%B %d, %Y")
    except Exception:
        return dt_str


def _generate_generic_8d_html(investigation: dict, actions: list[dict]) -> str:
    """Generate HTML for Generic 8D template."""
    # Group actions by discipline
    d3_actions = [a for a in actions if a.get("discipline") == "D3"]
    d5_actions = [a for a in actions if a.get("discipline") == "D5"]
    d6_actions = [a for a in actions if a.get("discipline") == "D6"]
    d7_actions = [a for a in actions if a.get("discipline") == "D7"]
    
    # Build action tables HTML
    def action_table_html(action_list):
        if not action_list:
            return "<p><em>No actions recorded</em></p>"
        rows = ""
        for action in action_list:
            rows += f"""
            <tr>
                <td>{action.get('description', 'N/A')}</td>
                <td>{action.get('owner_user_id', 'N/A')[:8]}</td>
                <td>{_format_date(action.get('due_date'))}</td>
                <td><span class="status-{action.get('status', 'open')}">{action.get('status', 'open').upper()}</span></td>
            </tr>
            """
        return f"""
        <table class="action-table">
            <thead>
                <tr><th>Action</th><th>Owner</th><th>Due Date</th><th>Status</th></tr>
            </thead>
            <tbody>{rows}</tbody>
        </table>
        """
    
    # Build root cause HTML
    root_causes_html = ""
    if investigation.get("root_causes"):
        root_causes_html = "<ol class='root-causes'>"
        for cause in investigation["root_causes"]:
            confidence = cause.get("confidence", 0)
            root_causes_html += f"""
            <li>
                <strong>{cause.get('cause', 'N/A')}</strong> 
                <span class="confidence">(Confidence: {confidence:.2%})</span>
                <p>{cause.get('explanation', '')}</p>
            </li>
            """
        root_causes_html += "</ol>"
    else:
        root_causes_html = "<p><em>Root cause analysis pending</em></p>"
    
    # Build 5-Why HTML
    five_why_html = ""
    if investigation.get("five_why_chain"):
        five_why_html = "<table class='five-why-table'>"
        five_why_html += "<thead><tr><th>Level</th><th>Question</th><th>Answer</th></tr></thead><tbody>"
        for item in investigation["five_why_chain"]:
            five_why_html += f"""
            <tr>
                <td>{item.get('level', 'N/A')}</td>
                <td>{item.get('question', 'N/A')}</td>
                <td>{item.get('answer', 'N/A')}</td>
            </tr>
            """
        five_why_html += "</tbody></table>"
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>8D Report - {investigation.get('investigation_number')}</title>
        <style>
            @page {{
                size: letter;
                margin: 0.75in;
                @bottom-right {{
                    content: "Page " counter(page) " of " counter(pages);
                    font-size: 9pt;
                    color: #666;
                }}
                @bottom-left {{
                    content: "Generated by Gravix Quality — gravix.com";
                    font-size: 9pt;
                    color: #666;
                }}
            }}
            body {{
                font-family: Arial, Helvetica, sans-serif;
                font-size: 11pt;
                line-height: 1.4;
                color: #333;
            }}
            h1 {{
                font-size: 20pt;
                color: #1e40af;
                border-bottom: 3px solid #1e40af;
                padding-bottom: 8px;
                margin-top: 0;
            }}
            h2 {{
                font-size: 14pt;
                color: #1e40af;
                margin-top: 24px;
                margin-bottom: 12px;
                border-bottom: 1px solid #ddd;
                padding-bottom: 4px;
            }}
            .cover-info {{
                margin: 20px 0;
                padding: 15px;
                background: #f3f4f6;
                border-left: 4px solid #1e40af;
            }}
            .cover-info div {{
                margin: 8px 0;
            }}
            .label {{
                font-weight: bold;
                display: inline-block;
                width: 150px;
            }}
            .severity-critical {{ color: #dc2626; font-weight: bold; }}
            .severity-major {{ color: #f59e0b; font-weight: bold; }}
            .severity-minor {{ color: #10b981; font-weight: bold; }}
            .action-table {{
                width: 100%;
                border-collapse: collapse;
                margin: 15px 0;
                font-size: 10pt;
            }}
            .action-table th {{
                background: #1e40af;
                color: white;
                padding: 8px;
                text-align: left;
                font-weight: bold;
            }}
            .action-table td {{
                border: 1px solid #ddd;
                padding: 8px;
            }}
            .action-table tr:nth-child(even) {{
                background: #f9fafb;
            }}
            .status-complete {{ color: #10b981; font-weight: bold; }}
            .status-in_progress {{ color: #f59e0b; font-weight: bold; }}
            .status-open {{ color: #6b7280; }}
            .root-causes {{
                margin: 15px 0 15px 20px;
            }}
            .root-causes li {{
                margin: 12px 0;
            }}
            .confidence {{
                color: #6b7280;
                font-size: 10pt;
            }}
            .five-why-table {{
                width: 100%;
                border-collapse: collapse;
                margin: 15px 0;
                font-size: 10pt;
            }}
            .five-why-table th {{
                background: #1e40af;
                color: white;
                padding: 8px;
                text-align: left;
            }}
            .five-why-table td {{
                border: 1px solid #ddd;
                padding: 8px;
                vertical-align: top;
            }}
            .five-why-table tr:nth-child(even) {{
                background: #f9fafb;
            }}
            .section {{
                page-break-inside: avoid;
            }}
            .signature-block {{
                margin-top: 30px;
                padding: 15px;
                border: 2px solid #1e40af;
                page-break-inside: avoid;
            }}
        </style>
    </head>
    <body>
        <h1>8D Corrective Action Report</h1>
        
        <div class="cover-info">
            <div><span class="label">Investigation Number:</span> {investigation.get('investigation_number', 'N/A')}</div>
            <div><span class="label">Title:</span> {investigation.get('title', 'N/A')}</div>
            <div><span class="label">Customer:</span> {investigation.get('customer_oem', 'N/A')}</div>
            <div><span class="label">Part Number:</span> {investigation.get('product_part_number', 'N/A')}</div>
            <div><span class="label">Severity:</span> <span class="severity-{investigation.get('severity', 'minor')}">{investigation.get('severity', 'N/A').upper()}</span></div>
            <div><span class="label">Created:</span> {_format_date(investigation.get('created_at'))}</div>
            <div><span class="label">Status:</span> {investigation.get('status', 'N/A').upper()}</div>
        </div>
        
        <div class="section">
            <h2>D1 — Team Formation</h2>
            <p><strong>Team Lead:</strong> {investigation.get('team_lead_user_id', 'N/A')}</p>
            <p><strong>Champion:</strong> {investigation.get('champion_user_id', 'N/A')}</p>
            <p><strong>Approver:</strong> {investigation.get('approver_user_id', 'N/A')}</p>
        </div>
        
        <div class="section">
            <h2>D2 — Problem Description</h2>
            <p><strong>What Failed:</strong> {investigation.get('what_failed', 'N/A')}</p>
            <p><strong>Where in Process:</strong> {investigation.get('where_in_process', 'N/A')}</p>
            <p><strong>When Detected:</strong> {_format_date(investigation.get('when_detected'))}</p>
            <p><strong>How Detected:</strong> {investigation.get('how_detected', 'N/A')}</p>
            <p><strong>Quantity Affected:</strong> {investigation.get('defect_quantity', 'N/A')} units</p>
        </div>
        
        <div class="section">
            <h2>D3 — Containment Actions</h2>
            {action_table_html(d3_actions)}
        </div>
        
        <div class="section">
            <h2>D4 — Root Cause Analysis</h2>
            {root_causes_html}
            {five_why_html if five_why_html else ''}
            {f"<p><strong>Escape Point:</strong> {investigation.get('escape_point')}</p>" if investigation.get('escape_point') else ''}
        </div>
        
        <div class="section">
            <h2>D5 — Corrective Actions</h2>
            {action_table_html(d5_actions)}
        </div>
        
        <div class="section">
            <h2>D6 — Verification</h2>
            {action_table_html(d6_actions)}
        </div>
        
        <div class="section">
            <h2>D7 — Preventive Actions</h2>
            {action_table_html(d7_actions)}
        </div>
        
        <div class="section">
            <h2>D8 — Closure</h2>
            {f"<p>{investigation.get('closure_summary', 'Investigation pending closure.')}</p>" if investigation.get('closure_summary') else '<p><em>Investigation pending closure.</em></p>'}
            {f"<p><strong>Lessons Learned:</strong> {investigation.get('lessons_learned')}</p>" if investigation.get('lessons_learned') else ''}
            {f"<p><strong>Closed:</strong> {_format_date(investigation.get('closed_at'))}</p>" if investigation.get('closed_at') else ''}
        </div>
        
        {f'''
        <div class="signature-block">
            <p><strong>Approved By:</strong> {investigation.get('approver_user_id', 'N/A')}</p>
            <p><strong>Date:</strong> {_format_date(investigation.get('closed_at'))}</p>
        </div>
        ''' if investigation.get('closed_at') else ''}
    </body>
    </html>
    """
    return html


def _generate_ford_8d_html(investigation: dict, actions: list[dict]) -> str:
    """Generate HTML for Ford Global 8D template.
    
    Differences from generic:
    - Adds D0 (Emergency Response Actions / ERA)
    - Includes escape point prominently in D4
    - Adds Ford severity rating format (S/O/D)
    """
    generic_html = _generate_generic_8d_html(investigation, actions)
    
    # Insert D0 section before D1
    d0_section = """
        <div class="section">
            <h2>D0 — Emergency Response Actions (ERA)</h2>
            <p><em>Immediate actions taken upon detection to protect the customer.</em></p>
            <p>{}</p>
        </div>
    """.format(investigation.get('d0_era', 'N/A'))
    
    # Insert after cover-info div
    generic_html = generic_html.replace(
        '<div class="section">',
        d0_section + '<div class="section">',
        1
    )
    
    # Update title
    generic_html = generic_html.replace(
        "8D Corrective Action Report",
        "Ford Global 8D Corrective Action Report"
    )
    
    return generic_html


async def generate_8d_pdf(
    investigation_id: str,
    template_key: str = "generic_8d",
) -> bytes:
    """Generate 8D report PDF from investigation data.
    
    Args:
        investigation_id: UUID of the investigation
        template_key: Template to use ('generic_8d' or 'ford_global_8d')
        
    Returns:
        PDF bytes
        
    Raises:
        ValueError: If investigation not found or template unknown
    """
    db = get_supabase()
    
    # Fetch investigation
    result = db.table("investigations").select("*").eq("id", investigation_id).execute()
    if not result.data:
        raise ValueError(f"Investigation {investigation_id} not found")
    
    investigation = result.data[0]
    
    # Fetch actions
    actions_result = (
        db.table("investigation_actions")
        .select("*")
        .eq("investigation_id", investigation_id)
        .order("discipline", desc=False)
        .execute()
    )
    actions = actions_result.data if actions_result.data else []
    
    # Generate HTML based on template
    if template_key == "generic_8d":
        html_content = _generate_generic_8d_html(investigation, actions)
    elif template_key == "ford_global_8d":
        html_content = _generate_ford_8d_html(investigation, actions)
    else:
        raise ValueError(f"Unknown template: {template_key}")
    
    # Render PDF with WeasyPrint
    try:
        pdf_bytes = HTML(string=html_content).write_pdf()
        logger.info(
            f"Generated {template_key} PDF for investigation {investigation.get('investigation_number')} "
            f"({len(pdf_bytes)} bytes)"
        )
        return pdf_bytes
    except Exception as e:
        logger.exception(f"Failed to generate PDF: {e}")
        raise ValueError(f"PDF generation failed: {str(e)}")
