"""Plan feature configuration — single source of truth for tier gating.

Every gated endpoint checks this dict via plan_gate() dependency.
Frontend reads the same gate keys via /users/me response.
"""

PLAN_FEATURES: dict[str, dict] = {
    "free": {
        "analysis.failure": True,
        "analysis.spec": True,
        "analysis.guided": True,
        "analysis.photos": False,
        "analysis.visual_ai": False,
        "analysis.tds_aware": False,
        "analysis.rerun": False,
        "history.export_pdf": False,
        "investigations.create": False,
        "investigations.view": False,
        "cases.browse": True,
        "cases.details": False,
        "products.browse": True,
        "products.extract_tds": False,
        "products.performance": False,
        "intelligence.alerts": False,
        "intelligence.trends": False,
        "platform.seats": False,
        "platform.sso": False,
        "platform.api": False,
        "rate_limits": {
            "monthly_analyses": 5,
            "monthly_specs": 5,
            "guided_turns": 10,
            "guided_sessions_monthly": 2,
        },
        "ai_output": {
            "root_causes_max": 2,
            "contributing_factors": False,
            "prevention_plan": False,
            "similar_cases": "hidden",
            "confidence_scores": False,
        },
    },
    "pro": {
        "analysis.failure": True,
        "analysis.spec": True,
        "analysis.guided": True,
        "analysis.photos": True,
        "analysis.visual_ai": True,
        "analysis.tds_aware": True,
        "analysis.rerun": True,
        "history.export_pdf": True,
        "investigations.create": False,
        "investigations.view": False,
        "cases.browse": True,
        "cases.details": True,
        "products.browse": True,
        "products.extract_tds": True,
        "products.performance": False,
        "intelligence.alerts": False,
        "intelligence.trends": False,
        "platform.seats": False,
        "platform.sso": False,
        "platform.api": False,
        "rate_limits": {
            "monthly_analyses": None,  # unlimited
            "monthly_specs": None,
            "guided_turns": 30,
            "guided_sessions_monthly": None,
        },
        "ai_output": {
            "root_causes_max": 5,
            "contributing_factors": True,
            "prevention_plan": True,
            "similar_cases": "count_only",
            "confidence_scores": True,
        },
    },
    "team": {  # team = quality in frontend (PlanContext normalizes)
        "analysis.failure": True,
        "analysis.spec": True,
        "analysis.guided": True,
        "analysis.photos": True,
        "analysis.visual_ai": True,
        "analysis.tds_aware": True,
        "analysis.rerun": True,
        "history.export_pdf": True,
        "investigations.create": True,
        "investigations.view": True,
        "cases.browse": True,
        "cases.details": True,
        "products.browse": True,
        "products.extract_tds": True,
        "products.performance": True,
        "intelligence.alerts": True,
        "intelligence.trends": True,
        "platform.seats": True,
        "platform.sso": False,
        "platform.api": False,
        "rate_limits": {
            "monthly_analyses": None,
            "monthly_specs": None,
            "guided_turns": 50,
            "guided_sessions_monthly": None,
        },
        "ai_output": {
            "root_causes_max": 5,
            "contributing_factors": True,
            "prevention_plan": True,
            "similar_cases": "full_detail_5",
            "confidence_scores": True,
        },
    },
    "enterprise": {
        # Everything in team + SSO + API + branding
        "analysis.failure": True,
        "analysis.spec": True,
        "analysis.guided": True,
        "analysis.photos": True,
        "analysis.visual_ai": True,
        "analysis.tds_aware": True,
        "analysis.rerun": True,
        "history.export_pdf": True,
        "investigations.create": True,
        "investigations.view": True,
        "cases.browse": True,
        "cases.details": True,
        "products.browse": True,
        "products.extract_tds": True,
        "products.performance": True,
        "intelligence.alerts": True,
        "intelligence.trends": True,
        "platform.seats": True,
        "platform.sso": True,
        "platform.api": True,
        "rate_limits": {
            "monthly_analyses": None,
            "monthly_specs": None,
            "guided_turns": 50,
            "guided_sessions_monthly": None,
        },
        "ai_output": {
            "root_causes_max": 5,
            "contributing_factors": True,
            "prevention_plan": True,
            "similar_cases": "full_detail_5",
            "confidence_scores": True,
        },
    },
}

MINIMUM_PLAN: dict[str, str] = {
    "analysis.photos": "pro",
    "analysis.visual_ai": "pro",
    "analysis.tds_aware": "pro",
    "analysis.rerun": "pro",
    "history.export_pdf": "pro",
    "cases.details": "pro",
    "products.extract_tds": "pro",
    "investigations.create": "team",
    "investigations.view": "team",
    "products.performance": "team",
    "intelligence.alerts": "team",
    "intelligence.trends": "team",
    "platform.seats": "team",
    "platform.sso": "enterprise",
    "platform.api": "enterprise",
}

UPGRADE_MESSAGES: dict[str, str] = {
    "analysis.photos": "Photo upload requires Pro ($49/mo).",
    "history.export_pdf": "PDF export requires Pro ($49/mo).",
    "cases.details": "Full case details require Pro ($49/mo).",
    "products.extract_tds": "TDS extraction requires Pro ($49/mo).",
    "investigations.create": "8D Investigations require Team ($149/mo).",
    "intelligence.alerts": "Pattern alerts require Team ($149/mo).",
    "platform.sso": "SSO requires Enterprise. Contact sales.",
}
